name: Run Tests

on:
  push:
    branches:
      - master
      - 'feature/*'
      - 'develop'
  pull_request:
    branches:
      - master
      - 'feature/*'
      - 'develop'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  


    - name: Install dependencies
      run: |
        npm install
        npm run prisma:generate

    - name: Run tests
      run: npm test


    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage/lcov-report/index.html  # Modify if your coverage is output elsewhere
