name: Run Tests

on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'develop'
  pull_request:
    branches:
      - main
      - 'feature/*'
      - 'develop'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify your Node.js version

    # Install dependencies
    - name: Install dependencies
      run: |
        npm install
        npm run prisma:generate

    # Run tests with Jest
    - name: Run tests
      run: npm test

    # Upload Jest coverage (optional)
    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage/lcov-report/index.html  # Modify if your coverage is output elsewhere
